[project]
name = "semantic-graph-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "semanticscholar>=0.11.0",
    "streamlit>=1.52.1",
    "streamlit-agraph>=0.0.45",
]
